// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nitikhon/golang-inventory-system/internal/core/port (interfaces: ItemRepository)

// Package mock_port is a generated GoMock package.
package mock_port

import (
        entity "github.com/nitikhon/golang-inventory-system/internal/core/entity"
        gorm "gorm.io/gorm"
        reflect "reflect"
        context "context"
        gomock "github.com/golang/mock/gomock"
)

// MockItemRepository is a mock of ItemRepository interface.
type MockItemRepository struct {
        ctrl     *gomock.Controller
        recorder *MockItemRepositoryMockRecorder
}

// MockItemRepositoryMockRecorder is the mock recorder for MockItemRepository.
type MockItemRepositoryMockRecorder struct {
        mock *MockItemRepository
}

// NewMockItemRepository creates a new mock instance.
func NewMockItemRepository(ctrl *gomock.Controller) *MockItemRepository {
        mock := &MockItemRepository{ctrl: ctrl}
        mock.recorder = &MockItemRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemRepository) EXPECT() *MockItemRepositoryMockRecorder {
        return m.recorder
}

// Create mocks base method.
func (m *MockItemRepository) Create(arg0 context.Context, arg1 *entity.Item) (*entity.Item, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Create", arg0, arg1)
        ret0, _ := ret[0].(*entity.Item)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockItemRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockItemRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockItemRepository) Delete(arg0 context.Context, arg1 uint) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Delete", arg0, arg1)
        ret0, _ := ret[0].(error)
        return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockItemRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockItemRepository)(nil).Delete), arg0, arg1)
}

// GetAllItems mocks base method.
func (m *MockItemRepository) GetAllItems(arg0 context.Context, arg1, arg2 int, arg3 string) (*entity.PaginationResult[entity.Item], error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllItems", arg0, arg1, arg2, arg3)
        ret0, _ := ret[0].(*entity.PaginationResult[entity.Item])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetAllItems indicates an expected call of GetAllItems.
func (mr *MockItemRepositoryMockRecorder) GetAllItems(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllItems", reflect.TypeOf((*MockItemRepository)(nil).GetAllItems), arg0, arg1, arg2, arg3)
}

// GetDB mocks base method.
func (m *MockItemRepository) GetDB() *gorm.DB {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetDB")
        ret0, _ := ret[0].(*gorm.DB)
        return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockItemRepositoryMockRecorder) GetDB() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockItemRepository)(nil).GetDB))
}

// GetItemByID mocks base method.
func (m *MockItemRepository) GetItemByID(arg0 context.Context, arg1 uint) (*entity.Item, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetItemByID", arg0, arg1)
        ret0, _ := ret[0].(*entity.Item)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockItemRepositoryMockRecorder) GetItemByID(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockItemRepository)(nil).GetItemByID), arg0, arg1)
}

// GetItemByIDForUpdate mocks base method.
func (m *MockItemRepository) GetItemByIDForUpdate(arg0 *gorm.DB, arg1 uint) (*entity.Item, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetItemByIDForUpdate", arg0, arg1)
        ret0, _ := ret[0].(*entity.Item)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetItemByIDForUpdate indicates an expected call of GetItemByIDForUpdate.
func (mr *MockItemRepositoryMockRecorder) GetItemByIDForUpdate(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByIDForUpdate", reflect.TypeOf((*MockItemRepository)(nil).GetItemByIDForUpdate), arg0, arg1)
}

// GetItemByName mocks base method.
func (m *MockItemRepository) GetItemByName(arg0 context.Context, arg1 string) (*entity.Item, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetItemByName", arg0, arg1)
        ret0, _ := ret[0].(*entity.Item)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetItemByName indicates an expected call of GetItemByName.
func (mr *MockItemRepositoryMockRecorder) GetItemByName(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByName", reflect.TypeOf((*MockItemRepository)(nil).GetItemByName), arg0, arg1)
}

// Update mocks base method.
func (m *MockItemRepository) Update(arg0 context.Context, arg1 *entity.Item) (*entity.Item, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Update", arg0, arg1)
        ret0, _ := ret[0].(*entity.Item)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockItemRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockItemRepository)(nil).Update), arg0, arg1)
}

// UpdateWithTx mocks base method.
func (m *MockItemRepository) UpdateWithTx(arg0 *gorm.DB, arg1 *entity.Item) (*entity.Item, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "UpdateWithTx", arg0, arg1)
        ret0, _ := ret[0].(*entity.Item)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockItemRepositoryMockRecorder) UpdateWithTx(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockItemRepository)(nil).UpdateWithTx), arg0, arg1)
}