// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/core/port/borrowing_port.go

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/nitikhon/golang-inventory-system/internal/core/entity"
	gorm "gorm.io/gorm"
)

// MockBorrowingRepository is a mock of BorrowingRepository interface.
type MockBorrowingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBorrowingRepositoryMockRecorder
}

// MockBorrowingRepositoryMockRecorder is the mock recorder for MockBorrowingRepository.
type MockBorrowingRepositoryMockRecorder struct {
	mock *MockBorrowingRepository
}

// NewMockBorrowingRepository creates a new mock instance.
func NewMockBorrowingRepository(ctrl *gomock.Controller) *MockBorrowingRepository {
	mock := &MockBorrowingRepository{ctrl: ctrl}
	mock.recorder = &MockBorrowingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowingRepository) EXPECT() *MockBorrowingRepositoryMockRecorder {
	return m.recorder
}

// ApproveBorrowingWithTx mocks base method.
func (m *MockBorrowingRepository) ApproveBorrowingWithTx(tx *gorm.DB, borrowingId, approverId uint) (*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBorrowingWithTx", tx, borrowingId, approverId)
	ret0, _ := ret[0].(*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveBorrowingWithTx indicates an expected call of ApproveBorrowingWithTx.
func (mr *MockBorrowingRepositoryMockRecorder) ApproveBorrowingWithTx(tx, borrowingId, approverId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBorrowingWithTx", reflect.TypeOf((*MockBorrowingRepository)(nil).ApproveBorrowingWithTx), tx, borrowingId, approverId)
}

// BorrowItem mocks base method.
func (m *MockBorrowingRepository) BorrowItem(borrowing *entity.Borrowing) (*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BorrowItem", borrowing)
	ret0, _ := ret[0].(*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BorrowItem indicates an expected call of BorrowItem.
func (mr *MockBorrowingRepositoryMockRecorder) BorrowItem(borrowing interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowItem", reflect.TypeOf((*MockBorrowingRepository)(nil).BorrowItem), borrowing)
}

// GetAllBorrowings mocks base method.
func (m *MockBorrowingRepository) GetAllBorrowings() ([]*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBorrowings")
	ret0, _ := ret[0].([]*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBorrowings indicates an expected call of GetAllBorrowings.
func (mr *MockBorrowingRepositoryMockRecorder) GetAllBorrowings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBorrowings", reflect.TypeOf((*MockBorrowingRepository)(nil).GetAllBorrowings))
}

// GetBorrowingByID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingByID(borrowingID uint) (*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowingByID", borrowingID)
	ret0, _ := ret[0].(*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowingByID indicates an expected call of GetBorrowingByID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingByID(borrowingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingByID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingByID), borrowingID)
}

// GetBorrowingsByApprovalStatus mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByApprovalStatus(status string) ([]*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowingsByApprovalStatus", status)
	ret0, _ := ret[0].([]*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowingsByApprovalStatus indicates an expected call of GetBorrowingsByApprovalStatus.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByApprovalStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByApprovalStatus", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByApprovalStatus), status)
}

// GetBorrowingsByApproverID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByApproverID(approverID uint) ([]*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowingsByApproverID", approverID)
	ret0, _ := ret[0].([]*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowingsByApproverID indicates an expected call of GetBorrowingsByApproverID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByApproverID(approverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByApproverID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByApproverID), approverID)
}

// GetBorrowingsByBorrowingStatus mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByBorrowingStatus(status string) ([]*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowingsByBorrowingStatus", status)
	ret0, _ := ret[0].([]*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowingsByBorrowingStatus indicates an expected call of GetBorrowingsByBorrowingStatus.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByBorrowingStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByBorrowingStatus", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByBorrowingStatus), status)
}

// GetBorrowingsByItemID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByItemID(itemID uint) ([]*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowingsByItemID", itemID)
	ret0, _ := ret[0].([]*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowingsByItemID indicates an expected call of GetBorrowingsByItemID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByItemID(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByItemID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByItemID), itemID)
}

// GetBorrowingsByUserID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByUserID(userID uint) ([]*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBorrowingsByUserID", userID)
	ret0, _ := ret[0].([]*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBorrowingsByUserID indicates an expected call of GetBorrowingsByUserID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByUserID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByUserID), userID)
}

// GetUserBorrowingStats mocks base method.
func (m *MockBorrowingRepository) GetUserBorrowingStats(userID uint) (*entity.BorrowingStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBorrowingStats", userID)
	ret0, _ := ret[0].(*entity.BorrowingStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBorrowingStats indicates an expected call of GetUserBorrowingStats.
func (mr *MockBorrowingRepositoryMockRecorder) GetUserBorrowingStats(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBorrowingStats", reflect.TypeOf((*MockBorrowingRepository)(nil).GetUserBorrowingStats), userID)
}

// RejectBorrowingWithTx mocks base method.
func (m *MockBorrowingRepository) RejectBorrowingWithTx(tx *gorm.DB, borrowingId, rejecterId uint) (*entity.Borrowing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectBorrowingWithTx", tx, borrowingId, rejecterId)
	ret0, _ := ret[0].(*entity.Borrowing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectBorrowingWithTx indicates an expected call of RejectBorrowingWithTx.
func (mr *MockBorrowingRepositoryMockRecorder) RejectBorrowingWithTx(tx, borrowingId, rejecterId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectBorrowingWithTx", reflect.TypeOf((*MockBorrowingRepository)(nil).RejectBorrowingWithTx), tx, borrowingId, rejecterId)
}
