// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nitikhon/golang-inventory-system/internal/core/port (interfaces: BorrowingRepository)

// Package mock_port is a generated GoMock package.
package mock_port

import (
        gomock "github.com/golang/mock/gomock"
        entity "github.com/nitikhon/golang-inventory-system/internal/core/entity"
        gorm "gorm.io/gorm"
        reflect "reflect"
)

// MockBorrowingRepository is a mock of BorrowingRepository interface.
type MockBorrowingRepository struct {
        ctrl     *gomock.Controller
        recorder *MockBorrowingRepositoryMockRecorder
}

// MockBorrowingRepositoryMockRecorder is the mock recorder for MockBorrowingRepository.
type MockBorrowingRepositoryMockRecorder struct {
        mock *MockBorrowingRepository
}

// NewMockBorrowingRepository creates a new mock instance.
func NewMockBorrowingRepository(ctrl *gomock.Controller) *MockBorrowingRepository {
        mock := &MockBorrowingRepository{ctrl: ctrl}
        mock.recorder = &MockBorrowingRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBorrowingRepository) EXPECT() *MockBorrowingRepositoryMockRecorder {
        return m.recorder
}

// ApproveBorrowingWithTx mocks base method.
func (m *MockBorrowingRepository) ApproveBorrowingWithTx(arg0 *gorm.DB, arg1, arg2 uint) (*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ApproveBorrowingWithTx", arg0, arg1, arg2)
        ret0, _ := ret[0].(*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ApproveBorrowingWithTx indicates an expected call of ApproveBorrowingWithTx.
func (mr *MockBorrowingRepositoryMockRecorder) ApproveBorrowingWithTx(arg0, arg1, arg2 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBorrowingWithTx", reflect.TypeOf((*MockBorrowingRepository)(nil).ApproveBorrowingWithTx), arg0, arg1, arg2)
}

// BorrowItem mocks base method.
func (m *MockBorrowingRepository) BorrowItem(arg0 *entity.Borrowing) (*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "BorrowItem", arg0)
        ret0, _ := ret[0].(*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// BorrowItem indicates an expected call of BorrowItem.
func (mr *MockBorrowingRepositoryMockRecorder) BorrowItem(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowItem", reflect.TypeOf((*MockBorrowingRepository)(nil).BorrowItem), arg0)
}

// GetAllBorrowings mocks base method.
func (m *MockBorrowingRepository) GetAllBorrowings() ([]*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetAllBorrowings")
        ret0, _ := ret[0].([]*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetAllBorrowings indicates an expected call of GetAllBorrowings.
func (mr *MockBorrowingRepositoryMockRecorder) GetAllBorrowings() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBorrowings", reflect.TypeOf((*MockBorrowingRepository)(nil).GetAllBorrowings))
}

// GetBorrowingByID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingByID(arg0 uint) (*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBorrowingByID", arg0)
        ret0, _ := ret[0].(*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBorrowingByID indicates an expected call of GetBorrowingByID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingByID(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingByID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingByID), arg0)
}

// GetBorrowingsByApprovalStatus mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByApprovalStatus(arg0 string) ([]*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBorrowingsByApprovalStatus", arg0)
        ret0, _ := ret[0].([]*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBorrowingsByApprovalStatus indicates an expected call of GetBorrowingsByApprovalStatus.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByApprovalStatus(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByApprovalStatus", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByApprovalStatus), arg0)
}

// GetBorrowingsByApproverID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByApproverID(arg0 uint) ([]*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBorrowingsByApproverID", arg0)
        ret0, _ := ret[0].([]*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBorrowingsByApproverID indicates an expected call of GetBorrowingsByApproverID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByApproverID(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByApproverID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByApproverID), arg0)
}

// GetBorrowingsByBorrowingStatus mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByBorrowingStatus(arg0, arg1 string, arg2, arg3 int) (*entity.PaginationResult[entity.Borrowing], error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBorrowingsByBorrowingStatus", arg0, arg1, arg2, arg3)
        ret0, _ := ret[0].(*entity.PaginationResult[entity.Borrowing])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBorrowingsByBorrowingStatus indicates an expected call of GetBorrowingsByBorrowingStatus.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByBorrowingStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByBorrowingStatus", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByBorrowingStatus), arg0, arg1, arg2, arg3)
}

// GetBorrowingsByItemID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByItemID(arg0 uint) ([]*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBorrowingsByItemID", arg0)
        ret0, _ := ret[0].([]*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBorrowingsByItemID indicates an expected call of GetBorrowingsByItemID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByItemID(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByItemID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByItemID), arg0)
}

// GetBorrowingsByUserID mocks base method.
func (m *MockBorrowingRepository) GetBorrowingsByUserID(arg0 uint, arg1, arg2 int, arg3 string) (*entity.PaginationResult[entity.Borrowing], error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetBorrowingsByUserID", arg0, arg1, arg2, arg3)
        ret0, _ := ret[0].(*entity.PaginationResult[entity.Borrowing])
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetBorrowingsByUserID indicates an expected call of GetBorrowingsByUserID.
func (mr *MockBorrowingRepositoryMockRecorder) GetBorrowingsByUserID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBorrowingsByUserID", reflect.TypeOf((*MockBorrowingRepository)(nil).GetBorrowingsByUserID), arg0, arg1, arg2, arg3)
}

// GetUserBorrowingStats mocks base method.
func (m *MockBorrowingRepository) GetUserBorrowingStats(arg0 uint) (*entity.BorrowingStats, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetUserBorrowingStats", arg0)
        ret0, _ := ret[0].(*entity.BorrowingStats)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetUserBorrowingStats indicates an expected call of GetUserBorrowingStats.
func (mr *MockBorrowingRepositoryMockRecorder) GetUserBorrowingStats(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBorrowingStats", reflect.TypeOf((*MockBorrowingRepository)(nil).GetUserBorrowingStats), arg0)
}

// HasActiveBorrowing mocks base method.
func (m *MockBorrowingRepository) HasActiveBorrowing(arg0, arg1 uint) (bool, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "HasActiveBorrowing", arg0, arg1)
        ret0, _ := ret[0].(bool)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// HasActiveBorrowing indicates an expected call of HasActiveBorrowing.
func (mr *MockBorrowingRepositoryMockRecorder) HasActiveBorrowing(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveBorrowing", reflect.TypeOf((*MockBorrowingRepository)(nil).HasActiveBorrowing), arg0, arg1)
}

// RejectBorrowingWithTx mocks base method.
func (m *MockBorrowingRepository) RejectBorrowingWithTx(arg0 *gorm.DB, arg1, arg2 uint) (*entity.Borrowing, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "RejectBorrowingWithTx", arg0, arg1, arg2)
        ret0, _ := ret[0].(*entity.Borrowing)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// RejectBorrowingWithTx indicates an expected call of RejectBorrowingWithTx.
func (mr *MockBorrowingRepositoryMockRecorder) RejectBorrowingWithTx(arg0, arg1, arg2 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectBorrowingWithTx", reflect.TypeOf((*MockBorrowingRepository)(nil).RejectBorrowingWithTx), arg0, arg1, arg2)
}