services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: lendit-app
        working_dir: /app
        ports:
            - "8080:8080"
        restart: unless-stopped
        volumes:
            - ./:/app
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/
            - ./docker/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
        ports:
            - "5432:5432"
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 5s
            timeout: 5s
            retries: 5

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            - postgres
        restart: unless-stopped

volumes:
    postgres_data: