package errormap

const (
	// Borrowing errors
	ErrUserNotExist              = "user does not exist or is not active"
	ErrItemNotAvailable          = "item is not available for borrowing"
	ErrItemNotEnough             = "item is not available enough to borrow"
	ErrAlreadyBorrowed           = "user has already borrowed this item and it is still pending"
	ErrBorrowingNotExist         = "borrowing does not exist"
	ErrApproverNotExist          = "approver does not exist or is not active"
	ErrRejecterNotExist          = "rejecter does not exist or is not active"
	ErrItemNotExistOrActive      = "item does not exist or is not active"
	ErrNotEnoughItemsForApproval = "not enough items available to approve borrowing"
	ErrBorrowingNotPending       = "borrowing request is not pending"

	// Item errors
	ErrItemNotFound            = "item not found"
	ErrItemNameAlreadyExists   = "item with this name already exists"
	ErrRecordNotFound          = "record not found"
	ErrInvalidJSONFormat       = "Invalid JSON format"
	ErrInvalidItemPayload      = "invalid item payload"
	ErrItemIDRequired          = "item ID is required for update"
	ErrNameRequired            = "name is required"
	ErrDescriptionRequired     = "description is required"
	ErrNameNotEmpty            = "name should not be empty"
	ErrAvailableAmountNegative = "available_amount cannot be negative"
	ErrTotalAmountPositive     = "total_amount must be greater than 0"
	ErrAvailableExceedsTotal   = "available_amount cannot exceed total_amount"
	ErrTotalLessThanAvailable  = "updated total_amount is less than item's available amount"
	ErrStatusRequired          = "status must be specified"
	ErrInvalidStatus           = "status must be one of: available, borrowed, maintenance, lost"

	// User errors
	ErrInvalidRequestBody   = "invalid request body"
	ErrUserIDRequired       = "user ID is required for update"
	ErrUserNotFound         = "user not found"
	ErrUserCredentialsExist = "a user with the provided credentials already exists"
	ErrEmailAlreadyTaken    = "email already taken"
	ErrPhoneAlreadyTaken    = "phone already taken"
	ErrUsernameRequired     = "username is required"
	ErrEmailRequired        = "email is required"
	ErrPasswordRequired     = "password is required"
	ErrPhoneRequired        = "phone is required"
	ErrFirstNameRequired    = "first name is required"
	ErrLastNameRequired     = "last name is required"
	ErrInvalidCredentials   = "invalid credentials"
	ErrRefreshTokenNotFound = "refresh token not found"
	ErrInvalidRefreshToken  = "invalid refresh token"
	ErrGetUpdatedUser       = "error while trying to get updated user"

	// User validation errors
	ErrEmailMinLength              = "email must be at least 6 characters long"
	ErrEmailMaxLength              = "email must not exceed 128 characters"
	ErrEmailValidationFailed       = "failed to validate email format"
	ErrInvalidEmailFormat          = "invalid email format"
	ErrPhoneDigits                 = "phone number must be exactly 10 digits"
	ErrUsernameValidationFailed    = "failed to validate username format"
	ErrUsernameInvalidChars        = "username can only contain alphabets, numbers, dots, and underscores"
	ErrUsernameLength              = "username must be 3-20 characters"
	ErrUsernameInvalidStartEnd     = "username cannot start or end with '.' or '_'"
	ErrUsernameInvalidSequence     = "username cannot contain '..', '__', '._', or '_.'"
	ErrPasswordMinLength           = "password must be at least 8 characters long"
	ErrPasswordMaxLength           = "password must not exceed 128 characters"
	ErrPasswordLowercase           = "password must contain at least one lowercase letter"
	ErrPasswordUppercase           = "password must contain at least one uppercase letter"
	ErrPasswordDigit               = "password must contain at least one digit"
	ErrPasswordSpecialChar         = "password must contain at least one special character"
	ErrFirstNameMaxLength          = "first name must not exceed 200 characters"
	ErrFirstNameValidationFailed   = "failed to validate first name format"
	ErrFirstNameInvalidChars       = "first name can only contain letters, spaces, hyphens, and apostrophes"
	ErrFirstNameConsecutiveSpecial = "first name cannot contain consecutive special characters or spaces"
	ErrFirstNameInvalidStartEnd    = "first name cannot start or end with space, hyphen, or apostrophe"
	ErrLastNameMaxLength           = "last name must not exceed 200 characters"
	ErrLastNameValidationFailed    = "failed to validate last name format"
	ErrLastNameInvalidChars        = "last name can only contain letters, spaces, hyphens, and apostrophes"
	ErrLastNameConsecutiveSpecial  = "last name cannot contain consecutive special characters or spaces"
	ErrLastNameInvalidStartEnd     = "last name cannot start or end with space, hyphen, or apostrophe"

	// jwt errors
	ErrInvalidToken = "invalid token"
	ErrInvalidClaims = "invalid claims"
)
