// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/util/jwt.go

// Package mock_util is a generated GoMock package.
package mock_util

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/nitikhon/golang-inventory-system/internal/core/entity"
)

// MockJWTUtil is a mock of JWTUtil interface.
type MockJWTUtil struct {
	ctrl     *gomock.Controller
	recorder *MockJWTUtilMockRecorder
}

// MockJWTUtilMockRecorder is the mock recorder for MockJWTUtil.
type MockJWTUtilMockRecorder struct {
	mock *MockJWTUtil
}

// NewMockJWTUtil creates a new mock instance.
func NewMockJWTUtil(ctrl *gomock.Controller) *MockJWTUtil {
	mock := &MockJWTUtil{ctrl: ctrl}
	mock.recorder = &MockJWTUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTUtil) EXPECT() *MockJWTUtilMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTUtil) GenerateAccessToken(user entity.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTUtilMockRecorder) GenerateAccessToken(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTUtil)(nil).GenerateAccessToken), user)
}

// GenerateRefreshToken mocks base method.
func (m *MockJWTUtil) GenerateRefreshToken(user entity.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJWTUtilMockRecorder) GenerateRefreshToken(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJWTUtil)(nil).GenerateRefreshToken), user)
}

// ValidateAccessToken mocks base method.
func (m *MockJWTUtil) ValidateAccessToken(tokenStr string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", tokenStr)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockJWTUtilMockRecorder) ValidateAccessToken(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockJWTUtil)(nil).ValidateAccessToken), tokenStr)
}

// ValidateRefreshToken mocks base method.
func (m *MockJWTUtil) ValidateRefreshToken(tokenStr string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", tokenStr)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockJWTUtilMockRecorder) ValidateRefreshToken(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockJWTUtil)(nil).ValidateRefreshToken), tokenStr)
}
